set(driver_base_src
        drivers/base/arch_topology.c
        drivers/base/attribute_container.c
        drivers/base/bus.c
        drivers/base/cacheinfo.c
        drivers/base/class.c
        drivers/base/component.c
        drivers/base/container.c
        drivers/base/core.c
        drivers/base/cpu.c
        drivers/base/dd.c
        drivers/base/devcon.c
        drivers/base/devcoredump.c
        drivers/base/devres.c
        drivers/base/devtmpfs.c
        drivers/base/driver.c
        drivers/base/firmware.c
        drivers/base/firmware_loader/fallback.c
        drivers/base/firmware_loader/fallback_table.c
        drivers/base/firmware_loader/main.c
        drivers/base/hypervisor.c
        drivers/base/init.c
        drivers/base/isa.c
        drivers/base/map.c
        drivers/base/memory.c
        drivers/base/module.c
        drivers/base/node.c
        drivers/base/pinctrl.c
        drivers/base/platform-msi.c
        drivers/base/platform.c
        drivers/base/power/clock_ops.c
        drivers/base/power/common.c
        drivers/base/power/domain.c
        drivers/base/power/domain_governor.c
        drivers/base/power/generic_ops.c
        drivers/base/power/main.c
        drivers/base/power/qos.c
        drivers/base/power/runtime.c
        drivers/base/power/sysfs.c
        drivers/base/power/trace.c
        drivers/base/power/wakeirq.c
        drivers/base/power/wakeup.c
        drivers/base/property.c
        drivers/base/regmap/regcache-flat.c
        drivers/base/regmap/regcache-lzo.c
        drivers/base/regmap/regcache-rbtree.c
        drivers/base/regmap/regcache.c
        drivers/base/regmap/regmap-ac97.c
        drivers/base/regmap/regmap-debugfs.c
        drivers/base/regmap/regmap-i2c.c
        drivers/base/regmap/regmap-irq.c
        drivers/base/regmap/regmap-mmio.c
        drivers/base/regmap/regmap-sccb.c
        drivers/base/regmap/regmap-sdw.c
        drivers/base/regmap/regmap-slimbus.c
        drivers/base/regmap/regmap-spi.c
        drivers/base/regmap/regmap-spmi.c
        drivers/base/regmap/regmap-w1.c
        drivers/base/regmap/regmap.c
        drivers/base/soc.c
        drivers/base/syscore.c
        drivers/base/test/test_async_driver_probe.c
        drivers/base/topology.c
        drivers/base/transport_class.c
        drivers/base/base.h
        drivers/base/firmware_loader/fallback.h
        drivers/base/firmware_loader/firmware.h
        drivers/base/power/power.h
        drivers/base/regmap/internal.h
        drivers/base/regmap/trace.h
        )