set(core_src
	
	kernel/audit.h
kernel/bpf/bpf_lru_list.h
kernel/bpf/disasm.h
kernel/bpf/map_in_map.h
kernel/bpf/percpu_freelist.h
kernel/cgroup/cgroup-internal.h
kernel/debug/debug_core.h
kernel/debug/kdb/kdb_private.h
kernel/events/internal.h
kernel/gcov/gcov.h
kernel/irq/debug.h
kernel/irq/internals.h
kernel/irq/settings.h
kernel/kexec_internal.h
kernel/livepatch/core.h
kernel/livepatch/patch.h
kernel/livepatch/transition.h
kernel/locking/lockdep_internals.h
kernel/locking/lockdep_states.h
kernel/locking/mcs_spinlock.h
kernel/locking/mutex-debug.h
kernel/locking/mutex.h
kernel/locking/qspinlock_paravirt.h
kernel/locking/qspinlock_stat.h
kernel/locking/rtmutex-debug.h
kernel/locking/rtmutex.h
kernel/locking/rtmutex_common.h
kernel/locking/rwsem.h
kernel/module-internal.h
kernel/power/power.h
kernel/printk/braille.h
kernel/printk/console_cmdline.h
kernel/printk/internal.h
kernel/rcu/rcu.h
kernel/rcu/rcu_segcblist.h
kernel/rcu/tree.h
kernel/rcu/tree_exp.h
kernel/rcu/tree_plugin.h
kernel/sched/autogroup.h
kernel/sched/cpudeadline.h
kernel/sched/cpupri.h
kernel/sched/features.h
kernel/sched/pelt.h
kernel/sched/sched-pelt.h
kernel/sched/sched.h
kernel/sched/stats.h
kernel/smpboot.h
kernel/time/ntp_internal.h
kernel/time/posix-timers.h
kernel/time/tick-internal.h
kernel/time/tick-sched.h
kernel/time/timekeeping.h
kernel/time/timekeeping_internal.h
kernel/trace/trace.h
kernel/trace/trace_benchmark.h
kernel/trace/trace_entries.h
kernel/trace/trace_events_filter_test.h
kernel/trace/trace_kprobe_selftest.h
kernel/trace/trace_output.h
kernel/trace/trace_probe.h
kernel/trace/trace_stat.h
kernel/trace/tracing_map.h
kernel/uid16.h
kernel/workqueue_internal.h
kernel/acct.c
kernel/async.c
kernel/audit.c
kernel/audit_fsnotify.c
kernel/audit_tree.c
kernel/audit_watch.c
kernel/auditfilter.c
kernel/auditsc.c
kernel/backtracetest.c
kernel/bounds.c
kernel/bpf/arraymap.c
kernel/bpf/bpf_lru_list.c
kernel/bpf/btf.c
kernel/bpf/cgroup.c
kernel/bpf/core.c
kernel/bpf/cpumap.c
kernel/bpf/devmap.c
kernel/bpf/disasm.c
kernel/bpf/hashtab.c
kernel/bpf/helpers.c
kernel/bpf/inode.c
kernel/bpf/local_storage.c
kernel/bpf/lpm_trie.c
kernel/bpf/map_in_map.c
kernel/bpf/offload.c
kernel/bpf/percpu_freelist.c
kernel/bpf/reuseport_array.c
kernel/bpf/sockmap.c
kernel/bpf/stackmap.c
kernel/bpf/syscall.c
kernel/bpf/tnum.c
kernel/bpf/verifier.c
kernel/bpf/xskmap.c
kernel/capability.c
kernel/cgroup/cgroup-v1.c
kernel/cgroup/cgroup.c
kernel/cgroup/cpuset.c
kernel/cgroup/debug.c
kernel/cgroup/freezer.c
kernel/cgroup/namespace.c
kernel/cgroup/pids.c
kernel/cgroup/rdma.c
kernel/cgroup/rstat.c
kernel/compat.c
kernel/configs.c
kernel/context_tracking.c
kernel/cpu.c
kernel/cpu_pm.c
kernel/crash_core.c
kernel/crash_dump.c
kernel/cred.c
kernel/debug/debug_core.c
kernel/debug/gdbstub.c
kernel/debug/kdb/kdb_bp.c
kernel/debug/kdb/kdb_bt.c
kernel/debug/kdb/kdb_debugger.c
kernel/debug/kdb/kdb_io.c
kernel/debug/kdb/kdb_keyboard.c
kernel/debug/kdb/kdb_main.c
kernel/debug/kdb/kdb_support.c
kernel/delayacct.c
kernel/dma.c
kernel/dma/coherent.c
kernel/dma/contiguous.c
kernel/dma/debug.c
kernel/dma/direct.c
kernel/dma/mapping.c
kernel/dma/noncoherent.c
kernel/dma/swiotlb.c
kernel/dma/virt.c
kernel/events/callchain.c
kernel/events/core.c
kernel/events/hw_breakpoint.c
kernel/events/ring_buffer.c
kernel/events/uprobes.c
kernel/exec_domain.c
kernel/exit.c
kernel/extable.c
kernel/fail_function.c
kernel/fork.c
kernel/freezer.c
kernel/futex.c
kernel/gcov/base.c
kernel/gcov/fs.c
kernel/gcov/gcc_3_4.c
kernel/gcov/gcc_4_7.c
kernel/groups.c
kernel/hung_task.c
kernel/iomem.c
kernel/irq/affinity.c
kernel/irq/autoprobe.c
kernel/irq/chip.c
kernel/irq/cpuhotplug.c
kernel/irq/debugfs.c
kernel/irq/devres.c
kernel/irq/dummychip.c
kernel/irq/generic-chip.c
kernel/irq/handle.c
kernel/irq/ipi.c
kernel/irq/irq_sim.c
kernel/irq/irqdesc.c
kernel/irq/irqdomain.c
kernel/irq/manage.c
kernel/irq/matrix.c
kernel/irq/migration.c
kernel/irq/msi.c
kernel/irq/pm.c
kernel/irq/proc.c
kernel/irq/resend.c
kernel/irq/spurious.c
kernel/irq/timings.c
kernel/irq_work.c
kernel/jump_label.c
kernel/kallsyms.c
kernel/kcmp.c
kernel/kcov.c
kernel/kexec.c
kernel/kexec_core.c
kernel/kexec_file.c
kernel/kmod.c
kernel/kprobes.c
kernel/ksysfs.c
kernel/kthread.c
kernel/latencytop.c
kernel/livepatch/core.c
kernel/livepatch/patch.c
kernel/livepatch/shadow.c
kernel/livepatch/transition.c
kernel/locking/lockdep.c
kernel/locking/lockdep_proc.c
kernel/locking/locktorture.c
kernel/locking/mutex-debug.c
kernel/locking/mutex.c
kernel/locking/osq_lock.c
kernel/locking/percpu-rwsem.c
kernel/locking/qrwlock.c
kernel/locking/qspinlock.c
kernel/locking/rtmutex-debug.c
kernel/locking/rtmutex.c
kernel/locking/rwsem-spinlock.c
kernel/locking/rwsem-xadd.c
kernel/locking/rwsem.c
kernel/locking/semaphore.c
kernel/locking/spinlock.c
kernel/locking/spinlock_debug.c
kernel/locking/test-ww_mutex.c
kernel/memremap.c
kernel/module.c
kernel/module_signing.c
kernel/notifier.c
kernel/nsproxy.c
kernel/padata.c
kernel/panic.c
kernel/params.c
kernel/pid.c
kernel/pid_namespace.c
kernel/power/autosleep.c
kernel/power/console.c
kernel/power/hibernate.c
kernel/power/main.c
kernel/power/poweroff.c
kernel/power/process.c
kernel/power/qos.c
kernel/power/snapshot.c
kernel/power/suspend.c
kernel/power/suspend_test.c
kernel/power/swap.c
kernel/power/user.c
kernel/power/wakelock.c
kernel/printk/braille.c
kernel/printk/printk.c
kernel/printk/printk_safe.c
kernel/profile.c
kernel/ptrace.c
kernel/range.c
kernel/rcu/rcu_segcblist.c
kernel/rcu/rcuperf.c
kernel/rcu/rcutorture.c
kernel/rcu/srcutiny.c
kernel/rcu/srcutree.c
kernel/rcu/sync.c
kernel/rcu/tiny.c
kernel/rcu/tree.c
kernel/rcu/update.c
kernel/reboot.c
kernel/relay.c
kernel/resource.c
kernel/rseq.c
kernel/sched/autogroup.c
kernel/sched/clock.c
kernel/sched/completion.c
kernel/sched/core.c
kernel/sched/cpuacct.c
kernel/sched/cpudeadline.c
kernel/sched/cpufreq.c
kernel/sched/cpufreq_schedutil.c
kernel/sched/cpupri.c
kernel/sched/cputime.c
kernel/sched/deadline.c
kernel/sched/debug.c
kernel/sched/fair.c
kernel/sched/idle.c
kernel/sched/isolation.c
kernel/sched/loadavg.c
kernel/sched/membarrier.c
kernel/sched/pelt.c
kernel/sched/rt.c
kernel/sched/stats.c
kernel/sched/stop_task.c
kernel/sched/swait.c
kernel/sched/topology.c
kernel/sched/wait.c
kernel/sched/wait_bit.c
kernel/seccomp.c
kernel/signal.c
kernel/smp.c
kernel/smpboot.c
kernel/softirq.c
kernel/stacktrace.c
kernel/stop_machine.c
kernel/sys.c
kernel/sys_ni.c
kernel/sysctl.c
kernel/sysctl_binary.c
kernel/task_work.c
kernel/taskstats.c
kernel/test_kprobes.c
kernel/time/alarmtimer.c
kernel/time/clockevents.c
kernel/time/clocksource.c
kernel/time/hrtimer.c
kernel/time/itimer.c
kernel/time/jiffies.c
kernel/time/ntp.c
kernel/time/posix-clock.c
kernel/time/posix-cpu-timers.c
kernel/time/posix-stubs.c
kernel/time/posix-timers.c
kernel/time/sched_clock.c
kernel/time/test_udelay.c
kernel/time/tick-broadcast-hrtimer.c
kernel/time/tick-broadcast.c
kernel/time/tick-common.c
kernel/time/tick-oneshot.c
kernel/time/tick-sched.c
kernel/time/time.c
kernel/time/timeconv.c
kernel/time/timecounter.c
kernel/time/timekeeping.c
kernel/time/timekeeping_debug.c
kernel/time/timer.c
kernel/time/timer_list.c
kernel/torture.c
kernel/trace/blktrace.c
kernel/trace/bpf_trace.c
kernel/trace/ftrace.c
kernel/trace/power-traces.c
kernel/trace/preemptirq_delay_test.c
kernel/trace/ring_buffer.c
kernel/trace/ring_buffer_benchmark.c
kernel/trace/rpm-traces.c
kernel/trace/trace.c
kernel/trace/trace_benchmark.c
kernel/trace/trace_branch.c
kernel/trace/trace_clock.c
kernel/trace/trace_event_perf.c
kernel/trace/trace_events.c
kernel/trace/trace_events_filter.c
kernel/trace/trace_events_hist.c
kernel/trace/trace_events_trigger.c
kernel/trace/trace_export.c
kernel/trace/trace_functions.c
kernel/trace/trace_functions_graph.c
kernel/trace/trace_hwlat.c
kernel/trace/trace_irqsoff.c
kernel/trace/trace_kdb.c
kernel/trace/trace_kprobe.c
kernel/trace/trace_kprobe_selftest.c
kernel/trace/trace_mmiotrace.c
kernel/trace/trace_nop.c
kernel/trace/trace_output.c
kernel/trace/trace_preemptirq.c
kernel/trace/trace_printk.c
kernel/trace/trace_probe.c
kernel/trace/trace_sched_switch.c
kernel/trace/trace_sched_wakeup.c
kernel/trace/trace_selftest.c
kernel/trace/trace_selftest_dynamic.c
kernel/trace/trace_seq.c
kernel/trace/trace_stack.c
kernel/trace/trace_stat.c
kernel/trace/trace_syscalls.c
kernel/trace/trace_uprobe.c
kernel/trace/tracing_map.c
kernel/tracepoint.c
kernel/tsacct.c
kernel/ucount.c
kernel/uid16.c
kernel/umh.c
kernel/up.c
kernel/user-return-notifier.c
kernel/user.c
kernel/user_namespace.c
kernel/utsname.c
kernel/utsname_sysctl.c
kernel/watchdog.c
kernel/watchdog_hld.c
kernel/workqueue.c
	)
