set(lib_src
        lib/842/842.h
        lib/842/842_debugfs.h
        lib/crc32defs.h
        lib/kstrtox.h
        lib/locking-selftest-hardirq.h
        lib/locking-selftest-mutex.h
        lib/locking-selftest-rlock-hardirq.h
        lib/locking-selftest-rlock-softirq.h
        lib/locking-selftest-rlock.h
        lib/locking-selftest-rsem.h
        lib/locking-selftest-rtmutex.h
        lib/locking-selftest-softirq.h
        lib/locking-selftest-spin-hardirq.h
        lib/locking-selftest-spin-softirq.h
        lib/locking-selftest-spin.h
        lib/locking-selftest-wlock-hardirq.h
        lib/locking-selftest-wlock-softirq.h
        lib/locking-selftest-wlock.h
        lib/locking-selftest-wsem.h
        lib/lz4/lz4defs.h
        lib/lzo/lzodefs.h
        lib/mpi/longlong.h
        lib/mpi/mpi-inline.h
        lib/mpi/mpi-internal.h
        lib/notifier-error-inject.h
        lib/raid6/x86.h
        lib/ubsan.h
        lib/xz/xz_lzma2.h
        lib/xz/xz_private.h
        lib/xz/xz_stream.h
        lib/zlib_deflate/defutil.h
        lib/zlib_inflate/inffast.h
        lib/zlib_inflate/inffixed.h
        lib/zlib_inflate/inflate.h
        lib/zlib_inflate/inftrees.h
        lib/zlib_inflate/infutil.h
        lib/zstd/bitstream.h
        lib/zstd/error_private.h
        lib/zstd/fse.h
        lib/zstd/huf.h
        lib/zstd/mem.h
        lib/zstd/zstd_internal.h
        lib/zstd/zstd_opt.h
        lib/842/842_compress.c
        lib/842/842_decompress.c
        lib/argv_split.c
        lib/ashldi3.c
        lib/ashrdi3.c
        lib/asn1_decoder.c
        lib/assoc_array.c
        lib/atomic64.c
        lib/atomic64_test.c
        lib/audit.c
        lib/bcd.c
        lib/bch.c
        lib/bitmap.c
        lib/bitrev.c
        lib/bsearch.c
        lib/btree.c
        lib/bucket_locks.c
        lib/bug.c
        lib/bust_spinlocks.c
        lib/chacha20.c
        lib/check_signature.c
        lib/checksum.c
        lib/clz_ctz.c
        lib/clz_tab.c
        lib/cmdline.c
        lib/cmpdi2.c
        lib/compat_audit.c
        lib/cordic.c
        lib/cpu_rmap.c
        lib/cpumask.c
        lib/crc-ccitt.c
        lib/crc-itu-t.c
        lib/crc-t10dif.c
        lib/crc16.c
        lib/crc32.c
        lib/crc32test.c
        lib/crc4.c
        lib/crc64.c
        lib/crc7.c
        lib/crc8.c
        lib/ctype.c
        lib/debug_info.c
        lib/debug_locks.c
        lib/debugobjects.c
        lib/dec_and_lock.c
        lib/decompress.c
        lib/decompress_bunzip2.c
        lib/decompress_inflate.c
        lib/decompress_unlz4.c
        lib/decompress_unlzma.c
        lib/decompress_unlzo.c
        lib/decompress_unxz.c
        lib/devres.c
        lib/digsig.c
        lib/div64.c
        lib/dump_stack.c
        lib/dynamic_debug.c
        lib/dynamic_queue_limits.c
        lib/earlycpio.c
        lib/error-inject.c
        lib/errseq.c
        lib/extable.c
        lib/fault-inject.c
        lib/fdt.c
        lib/fdt_empty_tree.c
        lib/fdt_ro.c
        lib/fdt_rw.c
        lib/fdt_strerror.c
        lib/fdt_sw.c
        lib/fdt_wip.c
        lib/find_bit.c
        lib/find_bit_benchmark.c
        lib/flex_array.c
        lib/flex_proportions.c
        lib/fonts/font_10x18.c
        lib/fonts/font_6x10.c
        lib/fonts/font_6x11.c
        lib/fonts/font_7x14.c
        lib/fonts/font_8x16.c
        lib/fonts/font_8x8.c
        lib/fonts/font_acorn_8x8.c
        lib/fonts/font_mini_4x6.c
        lib/fonts/font_pearl_8x8.c
        lib/fonts/font_sun12x22.c
        lib/fonts/font_sun8x16.c
        lib/fonts/fonts.c
        lib/gcd.c
        lib/gen_crc32table.c
        lib/gen_crc64table.c
        lib/genalloc.c
        lib/glob.c
        lib/globtest.c
        lib/hexdump.c
        lib/hweight.c
        lib/idr.c
        lib/inflate.c
        lib/int_sqrt.c
        lib/interval_tree.c
        lib/interval_tree_test.c
        lib/iomap.c
        lib/iomap_copy.c
        lib/iommu-helper.c
        lib/ioremap.c
        lib/iov_iter.c
        lib/irq_poll.c
        lib/irq_regs.c
        lib/is_single_threaded.c
        lib/jedec_ddr_data.c
        lib/kasprintf.c
        lib/kfifo.c
        lib/klist.c
        lib/kobject.c
        lib/kobject_uevent.c
        lib/kstrtox.c
        lib/lcm.c
        lib/libcrc32c.c
        lib/list_debug.c
        lib/list_sort.c
        lib/llist.c
        lib/locking-selftest.c
        lib/lockref.c
        lib/logic_pio.c
        lib/lru_cache.c
        lib/lshrdi3.c
        lib/lz4/lz4_compress.c
        lib/lz4/lz4_decompress.c
        lib/lz4/lz4hc_compress.c
        lib/lzo/lzo1x_compress.c
        lib/lzo/lzo1x_decompress_safe.c
        lib/memory-notifier-error-inject.c
        lib/memweight.c
        lib/mpi/generic_mpih-add1.c
        lib/mpi/generic_mpih-lshift.c
        lib/mpi/generic_mpih-mul1.c
        lib/mpi/generic_mpih-mul2.c
        lib/mpi/generic_mpih-mul3.c
        lib/mpi/generic_mpih-rshift.c
        lib/mpi/generic_mpih-sub1.c
        lib/mpi/mpi-bit.c
        lib/mpi/mpi-cmp.c
        lib/mpi/mpi-pow.c
        lib/mpi/mpicoder.c
        lib/mpi/mpih-cmp.c
        lib/mpi/mpih-div.c
        lib/mpi/mpih-mul.c
        lib/mpi/mpiutil.c
        lib/muldi3.c
        lib/net_utils.c
        lib/netdev-notifier-error-inject.c
        lib/nlattr.c
        lib/nmi_backtrace.c
        lib/nodemask.c
        lib/notifier-error-inject.c
        lib/of-reconfig-notifier-error-inject.c
        lib/oid_registry.c
        lib/once.c
        lib/parman.c
        lib/parser.c
        lib/pci_iomap.c
        lib/percpu-refcount.c
        lib/percpu_counter.c
        lib/percpu_test.c
        lib/plist.c
        lib/pm-notifier-error-inject.c
        lib/prime_numbers.c
        lib/radix-tree.c
        lib/raid6/algos.c
        lib/raid6/avx2.c
        lib/raid6/avx512.c
        lib/raid6/mktables.c
        lib/raid6/mmx.c
        lib/raid6/neon.c
        lib/raid6/recov.c
        lib/raid6/recov_avx2.c
        lib/raid6/recov_avx512.c
        lib/raid6/recov_neon.c
        lib/raid6/recov_neon_inner.c
        lib/raid6/recov_s390xc.c
        lib/raid6/recov_ssse3.c
        lib/raid6/sse1.c
        lib/raid6/sse2.c
        lib/raid6/test/test.c
        lib/random32.c
        lib/ratelimit.c
        lib/rational.c
        lib/rbtree.c
        lib/rbtree_test.c
        lib/reciprocal_div.c
        lib/reed_solomon/decode_rs.c
        lib/reed_solomon/encode_rs.c
        lib/reed_solomon/reed_solomon.c
        lib/refcount.c
        lib/rhashtable.c
        lib/sbitmap.c
        lib/scatterlist.c
        lib/seq_buf.c
        lib/sg_pool.c
        lib/sg_split.c
        lib/sha1.c
        lib/sha256.c
        lib/show_mem.c
        lib/siphash.c
        lib/smp_processor_id.c
        lib/sort.c
        lib/stackdepot.c
        lib/stmp_device.c
        lib/string.c
        lib/string_helpers.c
        lib/strncpy_from_user.c
        lib/strnlen_user.c
        lib/syscall.c
        lib/test-kstrtox.c
        lib/test-string_helpers.c
        lib/test_bitfield.c
        lib/test_bitmap.c
        lib/test_bpf.c
        lib/test_debug_virtual.c
        lib/test_firmware.c
        lib/test_hash.c
        lib/test_hexdump.c
        lib/test_ida.c
        lib/test_kasan.c
        lib/test_kmod.c
        lib/test_list_sort.c
        lib/test_module.c
        lib/test_overflow.c
        lib/test_parman.c
        lib/test_printf.c
        lib/test_rhashtable.c
        lib/test_siphash.c
        lib/test_sort.c
        lib/test_static_key_base.c
        lib/test_static_keys.c
        lib/test_string.c
        lib/test_sysctl.c
        lib/test_ubsan.c
        lib/test_user_copy.c
        lib/test_uuid.c
        lib/textsearch.c
        lib/timerqueue.c
        lib/ts_bm.c
        lib/ts_fsm.c
        lib/ts_kmp.c
        lib/ubsan.c
        lib/ucmpdi2.c
        lib/ucs2_string.c
        lib/usercopy.c
        lib/uuid.c
        lib/vsprintf.c
        lib/win_minmax.c
        lib/xxhash.c
        lib/xz/xz_crc32.c
        lib/xz/xz_dec_bcj.c
        lib/xz/xz_dec_lzma2.c
        lib/xz/xz_dec_stream.c
        lib/xz/xz_dec_syms.c
        lib/xz/xz_dec_test.c
        lib/zlib_deflate/deflate.c
        lib/zlib_deflate/deflate_syms.c
        lib/zlib_deflate/deftree.c
        lib/zlib_inflate/inffast.c
        lib/zlib_inflate/inflate.c
        lib/zlib_inflate/inflate_syms.c
        lib/zlib_inflate/inftrees.c
        lib/zlib_inflate/infutil.c
        lib/zstd/compress.c
        lib/zstd/decompress.c
        lib/zstd/entropy_common.c
        lib/zstd/fse_compress.c
        lib/zstd/fse_decompress.c
        lib/zstd/huf_compress.c
        lib/zstd/huf_decompress.c
        lib/zstd/zstd_common.c
        )