set(mm_src
        mm/backing-dev.c
        mm/balloon_compaction.c
        mm/bootmem.c
        mm/cleancache.c
        mm/cma.c
        mm/cma_debug.c
        mm/compaction.c
        mm/debug.c
        mm/debug_page_ref.c
        mm/dmapool.c
        mm/early_ioremap.c
        mm/fadvise.c
        mm/failslab.c
        mm/filemap.c
        mm/frame_vector.c
        mm/frontswap.c
        mm/gup.c
        mm/gup_benchmark.c
        mm/highmem.c
        mm/hmm.c
        mm/huge_memory.c
        mm/hugetlb.c
        mm/hugetlb_cgroup.c
        mm/hwpoison-inject.c
        mm/init-mm.c
        mm/interval_tree.c
        mm/kasan/kasan.c
        mm/kasan/kasan_init.c
        mm/kasan/quarantine.c
        mm/kasan/report.c
        mm/khugepaged.c
        mm/kmemleak-test.c
        mm/kmemleak.c
        mm/ksm.c
        mm/list_lru.c
        mm/maccess.c
        mm/madvise.c
        mm/memblock.c
        mm/memcontrol.c
        mm/memfd.c
        mm/memory-failure.c
        mm/memory.c
        mm/memory_hotplug.c
        mm/mempolicy.c
        mm/mempool.c
        mm/memtest.c
        mm/migrate.c
        mm/mincore.c
        mm/mlock.c
        mm/mm_init.c
        mm/mmap.c
        mm/mmu_context.c
        mm/mmu_notifier.c
        mm/mmzone.c
        mm/mprotect.c
        mm/mremap.c
        mm/msync.c
        mm/nobootmem.c
        mm/nommu.c
        mm/oom_kill.c
        mm/page-writeback.c
        mm/page_alloc.c
        mm/page_counter.c
        mm/page_ext.c
        mm/page_idle.c
        mm/page_io.c
        mm/page_isolation.c
        mm/page_owner.c
        mm/page_poison.c
        mm/page_vma_mapped.c
        mm/pagewalk.c
        mm/percpu-km.c
        mm/percpu-stats.c
        mm/percpu-vm.c
        mm/percpu.c
        mm/pgtable-generic.c
        mm/process_vm_access.c
        mm/quicklist.c
        mm/readahead.c
        mm/rmap.c
        mm/rodata_test.c
        mm/shmem.c
        mm/slab.c
        mm/slab_common.c
        mm/slob.c
        mm/slub.c
        mm/sparse-vmemmap.c
        mm/sparse.c
        mm/swap.c
        mm/swap_cgroup.c
        mm/swap_slots.c
        mm/swap_state.c
        mm/swapfile.c
        mm/truncate.c
        mm/usercopy.c
        mm/userfaultfd.c
        mm/util.c
        mm/vmacache.c
        mm/vmalloc.c
        mm/vmpressure.c
        mm/vmscan.c
        mm/vmstat.c
        mm/workingset.c
        mm/z3fold.c
        mm/zbud.c
        mm/zpool.c
        mm/zsmalloc.c
        mm/zswap.c
        mm/cma.h
        mm/internal.h
        mm/kasan/kasan.h
        mm/percpu-internal.h
        mm/slab.h
        )