set(virtual_device_src

        drivers/net/dummy.c
        drivers/net/eql.c
        drivers/net/geneve.c
        drivers/net/gtp.c
        drivers/net/ifb.c
        drivers/net/loopback.c
        drivers/net/macsec.c
        drivers/net/macvlan.c
        drivers/net/macvtap.c
        drivers/net/mdio.c
        drivers/net/mii.c
        drivers/net/netconsole.c
        drivers/net/net_failover.c
        drivers/net/nlmon.c
        drivers/net/ntb_netdev.c
        drivers/net/rionet.c
        drivers/net/sb1000.c
        drivers/net/Space.c
        drivers/net/sungem_phy.c
        drivers/net/tap.c
        drivers/net/thunderbolt.c
        drivers/net/tun.c
        drivers/net/veth.c
        drivers/net/virtio_net.c
        drivers/net/vrf.c
        drivers/net/vsockmon.c
        drivers/net/vxlan.c
        drivers/net/xen-netfront.c
        )