include_directories(${kernel_base}/net/wireguard/compat/simd/include)
include_directories(${kernel_base}/net/wireguard/crypto/include)
set(wg_src
        net/wireguard/compat/dst_cache/include/net/dst_cache.h
        net/wireguard/compat/memneq/include.h
        net/wireguard/compat/siphash/include/linux/siphash.h
        net/wireguard/compat/udp_tunnel/include/net/udp_tunnel.h
        net/wireguard/compat/udp_tunnel/udp_tunnel_partial_compat.h
        net/wireguard/compat/checksum/checksum_partial_compat.h
        net/wireguard/compat/compat-asm.h
        net/wireguard/compat/compat.h
        net/wireguard/compat/dstmetadata/include/net/dst_metadata.h
        net/wireguard/compat/fpu-x86/include/asm/fpu/api.h
        net/wireguard/compat/intel-family-x86/include/asm/intel-family.h
        net/wireguard/compat/neon-arm/include/asm/neon.h
        net/wireguard/compat/ptr_ring/include/linux/ptr_ring.h
        net/wireguard/compat/simd-asm/include/asm/simd.h
        net/wireguard/compat/simd/include/linux/simd.h
        net/wireguard/compat/skb_array/include/linux/skb_array.h
        net/wireguard/compat/version/linux/version.h
        net/wireguard/crypto/zinc/selftest/run.h
        net/wireguard/crypto/include/zinc/blake2s.h
        net/wireguard/crypto/include/zinc/chacha20.h
        net/wireguard/crypto/include/zinc/chacha20poly1305.h
        net/wireguard/crypto/include/zinc/curve25519.h
        net/wireguard/crypto/include/zinc/poly1305.h
        net/wireguard/crypto/zinc.h
        net/wireguard/allowedips.h
        net/wireguard/cookie.h
        net/wireguard/device.h
        net/wireguard/messages.h
        net/wireguard/netlink.h
        net/wireguard/noise.h
        net/wireguard/peer.h
        net/wireguard/peerlookup.h
        net/wireguard/queueing.h
        net/wireguard/ratelimiter.h
        net/wireguard/socket.h
        net/wireguard/timers.h
        net/wireguard/uapi/wireguard.h
        net/wireguard/version.h
        net/wireguard/allowedips.c
        net/wireguard/compat/dst_cache/dst_cache.c
        net/wireguard/compat/memneq/memneq.c
        net/wireguard/compat/siphash/siphash.c
        net/wireguard/compat/udp_tunnel/udp_tunnel.c
        net/wireguard/cookie.c
        net/wireguard/crypto/zinc/blake2s/blake2s.c
        net/wireguard/crypto/zinc/blake2s/blake2s-x86_64-glue.c
        net/wireguard/crypto/zinc/chacha20/chacha20-arm-glue.c
        net/wireguard/crypto/zinc/chacha20/chacha20.c
        net/wireguard/crypto/zinc/chacha20/chacha20-mips-glue.c
        net/wireguard/crypto/zinc/chacha20/chacha20-x86_64-glue.c
        net/wireguard/crypto/zinc/chacha20poly1305.c
        net/wireguard/crypto/zinc/curve25519/curve25519-arm-glue.c
        net/wireguard/crypto/zinc/curve25519/curve25519.c
        net/wireguard/crypto/zinc/curve25519/curve25519-fiat32.c
        net/wireguard/crypto/zinc/curve25519/curve25519-hacl64.c
        net/wireguard/crypto/zinc/curve25519/curve25519-x86_64.c
        net/wireguard/crypto/zinc/curve25519/curve25519-x86_64-glue.c
        net/wireguard/crypto/zinc/poly1305/poly1305-arm-glue.c
        net/wireguard/crypto/zinc/poly1305/poly1305.c
        net/wireguard/crypto/zinc/poly1305/poly1305-donna32.c
        net/wireguard/crypto/zinc/poly1305/poly1305-donna64.c
        net/wireguard/crypto/zinc/poly1305/poly1305-mips-glue.c
        net/wireguard/crypto/zinc/poly1305/poly1305-x86_64-glue.c
        net/wireguard/crypto/zinc/selftest/blake2s.c
        net/wireguard/crypto/zinc/selftest/chacha20.c
        net/wireguard/crypto/zinc/selftest/chacha20poly1305.c
        net/wireguard/crypto/zinc/selftest/curve25519.c
        net/wireguard/crypto/zinc/selftest/poly1305.c
        net/wireguard/device.c
        net/wireguard/main.c
        net/wireguard/netlink.c
        net/wireguard/noise.c
        net/wireguard/peer.c
        net/wireguard/peerlookup.c
        net/wireguard/queueing.c
        net/wireguard/ratelimiter.c
        net/wireguard/receive.c
        net/wireguard/selftest/allowedips.c
        net/wireguard/selftest/counter.c
        net/wireguard/selftest/ratelimiter.c
        net/wireguard/send.c
        net/wireguard/socket.c
        net/wireguard/timers.c
)